# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20161028_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_file',
        ),
    ]
