# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161111_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='knees',
            field=models.IntegerField(default=0),
        ),
    ]
